/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Entities.Team;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.text.DecimalFormat;

/**
 *
 * @author carlw
 */
public class HighScore extends javax.swing.JPanel {

    /**
     * Creates new form HighScore
     */
    int[] scores; 
    String[] names;
    DecimalFormat decimal = new DecimalFormat("###,###,###,##0.##");

    public HighScore(int[] score, String[] name) {
        scores = score;
        names = name;
        initComponents();
        repaint();
    }

    @Override
    public void paintComponent(Graphics g) {
        g.setColor(Color.BLACK);
        g.fillRect(0, 0, this.getWidth(), this.getHeight());
        g.setColor(Color.WHITE);
        g.setFont(new Font("OCR A Extended", Font.PLAIN, 48));
        g.drawString("Game Over", 0, 48);
        g.setFont(new Font("OCR A Extended", Font.PLAIN, 24));
        g.drawString("End Scores", 10, 84);
        g.setFont(new Font("OCR A Extended", Font.PLAIN, 12));
        for (int x = 0; x < scores.length; x++) {
            g.setColor(Color.WHITE);
            g.drawRect(10, (x+1) * 24 + 72, 12, 12);
            g.setColor(Team.getColor(x+1));
            g.drawString( names[x] + ":  " + decimal.format(scores[x]) + " pts", 35, (x+1) * 24 + 82);
            g.fillRect(10, (x+1) * 24 + 72, 12, 12);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
