/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Entities.Saviour;
import Entities.Team;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.io.FileNotFoundException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author carlw
 */
public class HighScore extends javax.swing.JPanel {

    /**
     * Creates new HighScore
     */
    int[] scores;
    String[] names;
    DecimalFormat decimal = new DecimalFormat("###,###,###,##0.##");

    /**
     * makes a high score screen
     *
     * @param score the score of the players at the end of the game
     * @param name the name of the players
     */
    public HighScore(int[] score, String[] name) {
        scores = score;
        names = name;
        initComponents();
        repaint();
    }

    @Override
    public void paintComponent(Graphics g) {
        //paints the high scores
        g.setColor(Color.BLACK);
        g.fillRect(0, 0, this.getWidth(), this.getHeight());
        g.setColor(Color.WHITE);
        g.setFont(new Font("OCR A Extended", Font.PLAIN, 48));
        g.drawString("Game Over", 0, 48);
        g.setFont(new Font("OCR A Extended", Font.PLAIN, 24));
        //the end scores
        g.drawString("End Scores", 10, 84);
        g.setFont(new Font("OCR A Extended", Font.PLAIN, 12));
        for (int x = 0; x < scores.length; x++) {
            g.setColor(Color.WHITE);
            g.drawRect(10, (x + 1) * 24 + 72, 12, 12);
            g.setColor(Team.getColor(x + 1));
            g.drawString(names[x] + ":  " + decimal.format(scores[x]) + " pts", 35, (x + 1) * 24 + 82);
            g.fillRect(10, (x + 1) * 24 + 72, 12, 12);
        }
        g.setColor(Color.WHITE);
        g.setFont(new Font("OCR A Extended", Font.PLAIN, 24));
        //the high scores
        g.drawString("High Scores", 200, 84);
        g.setFont(new Font("OCR A Extended", Font.PLAIN, 12));
        try {
            ArrayList<Team> high = Saviour.loadScore();
            int score = 0;
            for (int x = 0; x < 3; x++) {
                for (int i = 1; i < high.size(); i++) {
                    if (high.get(score).compareTo(high.get(i)) > 0) {
                        score = i;
                    }
                }
                g.drawString(high.get(score).getName() + ":  " + decimal.format(high.get(score).getScore()) + " pts", 200, (x + 1) * 24 + 82);
                high.remove(score);
                score = 0;
            }
        } catch (FileNotFoundException ex) {
            //if the high score don't exist
            System.out.println("No High Score File!!");
            g.drawString("No High Score File!!", 200, 94);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
