/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Entities.Map;
import Entities.Team;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.text.DecimalFormat;

/**
 *
 * @author Jia Jia Chen
 */
public class Scoreboard extends javax.swing.JPanel {

    DecimalFormat decimal = new DecimalFormat("###,###,###,##0.##");
    private Map map;
    int[] scores;
    String[] names;

    /**
     * Creates new form Scoreboard
     */
    public Scoreboard() {
        initComponents();
    }

    /**
     * Sets the map for the scoreboard to paint
     *
     * @param map
     */
    public void linkMap(Map map) {
        this.map = map;
        scores = map.getScores();
        names = map.getNames();
    }

    //Scoreboard to be refreshed by the game panel (TestingPanel)
    public void paintComponent(Graphics g) {
        g.setFont(new Font("TimesRoman", Font.BOLD, 12));
        g.setColor(Color.WHITE);
        g.fillRect(0, 0, this.getWidth(), this.getHeight());
        g.setColor(Color.BLACK);
        g.drawString("Time:  " + decimal.format(map.getTime() * 10) + " / " + decimal.format(Map.maxTime * 10) + " ms", 10, 25);
        g.drawLine(10, 40, this.getWidth() - 10, 40);
        scores = map.getScores();
        //Supports as many teams as you want
        for (int x = 0; x < scores.length; x++) {
            g.setColor(Color.BLACK);
            g.drawRect(10, (x + 1) * 25 + 30, 10, 10);
            g.drawString(names[x] + ":  " + decimal.format(scores[x]) + " pts", 35, (x + 1) * 25 + 40);
            g.setColor(Team.getColor(x + 1));
            g.fillRect(10, (x + 1) * 25 + 30, 10, 10);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 151, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
